# Generated by Django 4.1.3 on 2022-11-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_category_alter_product_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
